image: Visual Studio 2019

environment:
  CMAKE_PREFIX_PATH: "C:\\Qt\\6.0.0\\msvc2019_64"
  OpenCV_DIR: "C:\\tools\\opencv\\Build\\x64\\vc15\\lib"

platform: x64

configuration: Release

install:
  - choco install opencv
  - appveyor DownloadFile https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.7.1.zip -FileName libtorch.zip
  - 7z x libtorch.zip -oC:\tools\libtorch -aos

cache:
  - libtorch.zip -> appveyor.yml
  - C:\tools\libtorch -> appveyor.yml
  - C:\tools\opencv -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build:
  project: ALL_BUILD.vcxproj

before_build:
  - cmake .

after_build:
  - "C:\\Qt\\6.0.0\\msvc2019_64\\bin\\windeployqt.exe Release\\qanji_scanner.exe"
  - "xcopy C:\\tools\\opencv\\Build\\x64\\vc15\\bin\\*.dll Release"

artifacts:
  - path: Release
    name: "$(APPVEYOR_PROJECT_NAME)$(APPVEYOR_BUILD_VERSION)"

deploy:
  - provider: GitHub
    description: "Pre-built binaries for $(APPVEYOR_BUILD_VERSION)"
    artifact: "$(APPVEYOR_PROJECT_NAME)$(APPVEYOR_BUILD_VERSION)"
    auth_token:
      secure: ejf850Qb9gnwPX1as/psNqi147kBFGNoy9tmyytr//rC4GUHgf4SmUxZOuRWlBoG
    on:
      branch: master